[package]
name = "example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
ckandex = { path = "../lib", features = ["server"] }
tokio = { version = "1.26.0", features = ["full"] }
