[package]
name = "rest-api"
version = "0.0.0"
edition = "2021"

[dependencies]
ckandex = { path = "../../ckandex", features = ["server"] }
dotenv = "0.15.0"
tokio = { version = "1.26.0", features = ["full"] }
